version: '5'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb-container
    ports:
      - "27017:27017"
  backend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: my-backend-container
    ports:
      - "5555:5555"
    links:
      - mongodb
    depends_on:
      - mongodb
